### ISSUE TITLE
"main" is wrong in package.json

### ISSUE THREAD

**Issue by Jameskmonger** [pankajladhar/run-git-command#3]
`main` in `package.json` points to `index.js`, but the actual path is `dist/index.js`.

This is completely breaking and prevents the package from being imported.

**Comment by pankajladhar** [comment]
Thanks for pointing out.
I will look into this ASAP.

**Comment by pankajladhar** [comment]
@Jameskmonger I have again published `run-git-command`. It pointing to correct index.js.
