### ISSUE TITLE
Executor Options Dead Link

### ISSUE THREAD

**Issue by justin-lyon** [pankajladhar/run-git-command#4]
The link to Executor Options is dead. I'd like to see more documentation especially around using ssh to authenticate with my repo.

**Comment by pankajladhar** [comment]
I will fix  Executor Options link.

could you please elaborate more on `more documentation especially around using ssh to authenticate with my repo.`

**Comment by justin-lyon** [comment]
Certainly. I was expecting to find details on cloning a repository using run-git-command. As part of cloning the repository, I would expect there to be an option to use username/password or ssh to connect to the repository.

My goal is to clone a repository using run-git-command.

**Comment by pankajladhar** [comment]
I have fixed Executor Options Dead Link.
